### ISSUE TITLE
motivation

### ISSUE THREAD

**Issue by itslukej** [itslukej/Beemo#4]
developer has no motivation

**Comment by iczero** [comment]
oh noes

**Comment by Pandentia** [comment]
I don't see how a bug and enhancement could be invalid, a question and wontfix.

**Comment by iczero** [comment]
I don't see why a wontfix/question would be self-assigned.

**Comment by itslukej** [comment]
@Pandentia because fuck you, thats why

**Comment by Pandentia** [comment]
:ok_hand:

**Comment by Cat-who-loves-bots** [comment]
lal

**Comment by iczero** [comment]
lel

**Comment by Bowserinator** [comment]
lol

**Comment by Cat-who-loves-bots** [comment]
gud memes

**Comment by Cat-who-loves-bots** [comment]
@itslukej motivation needer look at [this](https://github.com/itslukej/Beemo/pull/5) and merge or banne
