### ISSUE TITLE
Add website to beemo

### ISSUE THREAD

**Issue by itslukej** [itslukej/Beemo#7]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40617558)](https://www.bountysource.com/issues/40617558-add-website-to-beemo?utm_source=40617558&utm_medium=shield&utm_campaign=ISSUE_BADGE)

kinda some shit like this https://github.com/GusCaplan/googlebot

to explain a bit more:

I wish for Beemo's current website(look at my repos) to be ported into node.js, running under the same script as beemo.

**Comment by MicroDroid** [comment]
Is it a requirement to be in NodeJS?

**Comment by itslukej** [comment]
@MicroDroid 1) Yes

2) I wish for itslukej/beemo-website to be ported into nodejs, which would run in app.js

**Comment by MicroDroid** [comment]
@itslukej Okay, I'll see if I can make this. I'll notify you if I actually start building the port

**Comment by itslukej** [comment]
@MicroDroid Make sure you hit the big "Get Started" button at the bountysource 👍

**Comment by MicroDroid** [comment]
@itslukej ack!
